### PR TITLE
fix USSD CDR issue not being saved to DB

### PR DESCRIPTION
**Pull request by croufay**
the CDR is now updated in the db for USSD request

### CODE REVIEW

**Comment by maria-farooq** [comment]
@croufay can you please share your findings about root cause why cdr was not being updated.
I see from code that eliminating following 2 conditions you were able to successfully add cdr:

1. `if (CallResponse.class.equals(klass)) {`
2. `if (callInfo.direction().equals("inbound")) {`

eliminating 1 is valid in my opinion as `klass` here can be either one of `CallResponse` or `SipServletRequest`.

But can you explain why you removed second check `if (callInfo.direction().equals("inbound")) `
As per my understanding `inbound` cdr is populated by `Interpreter` and `outbound` cdr is populated by `Call`/`UssdCall`.

But maybe i am missing something so you can help me here..

**Comment by maria-farooq** [comment]
@croufay do we have any update here?

**Comment by croufay** [comment]
@maria-farooq ,

When I sent USSD request, the if (callInfo.direction().equals("inbound")) 

didn't contain the word "inbound" so that part of the code was always false hence, not CDR will be recorded. I think this was because part of the USSD interpreter was copied from the VoiceInterpreter that had the inbound in the callInfo.direction.

Regards


Charles Roufay
Telestax

**Comment by maria-farooq** [comment]
thank for update @croufay i will merge it now

**Pull request merged**
