### PR TITLE
Fixes #2038 remove yeloow color in text box of login page

### LINKED ISSUE #2038: Remove the yellow color
screen shot 2017-04-06 at 1 12 03 pm

### PR DESCRIPTION
**Pull request by nguyenhien1807**
Dear @ammendonca and @ipsilantide ,

Please help me to review changes for issue 2038.

Best Regards,
Hien Nguyen

### CODE REVIEW

**Comment by ipsilantide** [comment]
Nice @nguyenhien1807 Can you same way remove this?
blue

**Comment by nguyenhien1807** [comment]
Hello @ipsilantide , 

I'm sorry but I didn't get your point clearly hence I just want to confirm again before processing to commit code changed. :) 

Do you mean that same way I need to remove yellow color in Olympus web? Is my understanding correct?

**Comment by ipsilantide** [comment]
Hello @nguyenhien1807 

No I mean to remove the blue when element receives focus :)

**Comment by nguyenhien1807** [comment]
Hello @ipsilantide ,

I got your point now! :)

I've checked with two pages (Restcomm login and Olympus login) I found out same things in both of them, should I apply the same fix for both?

Here're screenshots of RestComm login page:

screen shot 2017-06-15 at 9 38 41 pm
screen shot 2017-06-15 at 9 38 59 pm

Here're screenshots of Olympus login page:

screen shot 2017-06-15 at 9 39 07 pm
screen shot 2017-06-15 at 9 43 14 pm

**Comment by ipsilantide** [comment]
Sure @nguyenhien1807 wherever you find them kill them! :D
thanks

**Comment by ammendonca** [comment]
Hi @nguyenhien1807,

The end result is a bit too white, compared to when no autofill is used, see both screenshots. I think we need to keep the grey background in both cases, right @ipsilantide ?

> With autofill
image

> Without autofill
image

**Comment by ipsilantide** [comment]
@ammendonca this type of lines is better to be used in white background. I wouldn't like to make Dashboards sigh in page exactly the same with Olympus. Lets wait a bit cause at the end we might change this page to full grey and give to Olympus a more colored sign in page. wdyt?

@nguyenhien1807  can we also change the fonts here to be similar with the dashboard's? 
screen shot 2017-06-16 at 9 25 54 am

**Comment by nguyenhien1807** [comment]
@ipsilantide yes sure, we can change it as well as yellow/blue/red color. I've forked and cloned Olympus code to my local machine. After applying fixes, I'll make pull request for that.

**Pull request closed without merging**
