### PR TITLE
Issue 977

### PR DESCRIPTION
**Pull request by zahidMed**
This is a pull request for issue #977.

### CODE REVIEW

**Comment by deruelle** [comment]
@zahidMed can you please rebase your changes against latest master as the pull request seems to have conflicts ?

**Comment by zahidMed** [comment]
@deruelle 
I am confused, when rebasing the branch 977 it shows the message: Rebase did nothing. Head was already up-to-date. Even when creating a pull request, I can see only my changes.

Did I missed some thing?

**Comment by deruelle** [comment]
@gvagenas can you help here ?

**Comment by gvagenas** [comment]
Thanks @zahidMed , I am checking your work now and will update you.

**Comment by gvagenas** [comment]
@zahidMed you need to rebase (https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview) or merge with master branch to get the latest changes and then resolve any conflicts (https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/). 

I tried to rebase against latest master and resolved conflicts, you can check branch zahidMed-Issue-977.
Run the following in your branch : 
git pull git@github.com:RestComm/RestComm-Connect.git zahidMed-Issue-977

So please update your branch with the one i provided, and check again if any logging statement is not guarded. Also compile with maven to make sure there are no other issues (mvn clean install -Dmaven.test.skip).

Also, related to the issue you are currently working, consider moving logging to a service actor, see issue https://github.com/RestComm/Restcomm-Connect/issues/20 and lets discuss it when you are ready.

**Comment by gvagenas** [comment]
@zahidMed did you manage to reformat code so the compilation pass? As I told you in my last comment, your code currently fails to compile because of the maven style plugin and your work needs to be reformated.
Run "mvn clean install -Dmaven.test.skip" and check the error messages

Thanks, George

**Comment by zahidMed** [comment]
@gvagenas the checkstyle format is done, please check.

**Comment by gvagenas** [comment]
@zahidMed thanks for your work here. PR is now ok and project compiles. I reviewed the changed and merged to master.

MyBatisDaoManager
VoiceRSSSpeechSynthesizerTest

**Pull request merged**
