### PR TITLE
Issue380 presence rest api

### PR DESCRIPTION
**Pull request by ghjansen**
Issue380 presence rest api

### CODE REVIEW

**Comment by ghjansen** [comment]
@gvagenas most of the issues i had on testsuite after merging were caused by SQL scripts. I've adjusted related tests and now they are all green. Please, let me know if you find something else. :)

**Comment by deruelle** [comment]
@ghjansen can you rebase again it seems there is conflicts now ?

**Comment by ghjansen** [comment]
@deruelle @gvagenas able to merge again.

**Comment by ghjansen** [comment]
Closed without merging via #2454. Related to #2447.

**Pull request closed without merging**
