### PR TITLE
Video recording RCML

### PR DESCRIPTION
**Pull request by ghjansen**

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @ghjansen ! @gvagenas @hrosa can you review as time permits ?

**Comment by ghjansen** [comment]
Cool, my pleasure @deruelle !
I was planning to merge this PR along with Play verb and audio stability issues into a separated branch, so we test everything apart from master (but with all from it) before merging it to master. Wdyt?

**Comment by deruelle** [comment]
sure we can do that. Independent reviews of the smaller PRs still make sense in terms of overall design I think

**Comment by ghjansen** [comment]
Ah ok, great. Thanks!

**Comment by ghjansen** [comment]
Closed without merging via #2452. Related to #2447.

**Pull request closed without merging**
