### PR TITLE
Issue #1712: Accounts API - dont return .json suffix for Uri resource

### PR DESCRIPTION
**Pull request by abdulazizali77**
This is also related to #898 
@otsakir @deruelle This PR might not be applicable if we *change our minds*

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @abdulazizali77. @otsakir please review

**Comment by deruelle** [comment]
@abdulazizali77 we may change our mind as part of #898  review but at least the uri is consistent with the API call that was made. 
#898 should solve the inconsistencies across the board but it may take a bit of time to fix them all so I'm fine with moving forward on consistency iteratively

**Comment by abdulazizali77** [comment]
@otsakir please rereview
An alternative fix without modifying method signatures wouldve been to check against request.getCintentType() == 'application/json', bit kludgy but wouldnt have to pass an extra param, tell me what you think.

**Comment by otsakir** [comment]
@abdulazizali77, i think it will work for now. It's better to put an exception to the rule in the upper layers (endpoint) like you did than hide it in the converter. Let me get on with the merge..

**Comment by otsakir** [comment]
Hmmm, @abdulazizali77, the concept does not work. `createFrom()` is not involved when returning accounts. Only when creating new ones. The initial approach seems better after all.

In AccountConverter.java, i would overload prefix() so that it takes an additional content type parameter and use this overloated version from `writeUri(final URI uri, final JsonObject object) ` which i _know_ works for JSON content type. wdyt ?

**Comment by abdulazizali77** [comment]
@otsakir I agree with your idea but i would rather use MediaType like everywhere else
<pre>private String prefix(final Account account, final MediaType responseType) </pre>
What do you think?
This would also mean that we wouldnt be using the persisted uri at all in returning the response! We will address that issue later
I realize now that my prior implementation wouldve mapped a specific Account ID to either XML or JSON uri, when it shouldnt actually be exclusively either!

**Comment by otsakir** [comment]
> @otsakir I agree with your idea but i would rather use MediaType like everywhere else

ok @abdulazizali77, sounds great. 

> This would also mean that we wouldnt be using the persisted uri at all in returning the response!

Hmm, indeed. Wondering whether we should involve the data layer or not here. Btw, there has also been a suggestion in the past to get rid of content-type suffixes (.json etc.) and use the respective http headers instead. What is your opinion on that ?

> I realize now that my prior implementation wouldve mapped a specific Account ID to either XML or JSON uri, when it shouldnt actually be exclusively either!

well, that's what PRs are for. A second pair of eyes never harmed anyone ;-)

**Comment by abdulazizali77** [comment]
> well, that's what PRs are for. A second pair of eyes never harmed anyone ;-)
Ha, im sure everyone has had 'extreme programming' with three engineers and one manager behind them.... :D

**Comment by abdulazizali77** [comment]
>Btw, there has also been a suggestion in the past to get rid of content-type suffixes (.json etc.) and use the respective http headers instead. What is your opinion on that ?
String/URI rewriting is a bad thing i feel, but i think we should support and standardize what we have right now for this version and add content type header based webservices in the next version on top of the hopefully deprecated suffix based one

**Comment by abdulazizali77** [comment]
@otsakir ready

**Comment by gvagenas** [comment]
Thanks @abdulazizali77. Thanks @otsakir for review. PR is merged

**Pull request merged**
