### PR TITLE
Issue 1070 - added a transition when conference state changes to COMPLETED

### PR DESCRIPTION
**Pull request by maria-farooq**
@gvagenas please review

### CODE REVIEW

**Comment by maria-farooq** [comment]
tests are failing

`Results :

Failed tests: 
  ApplicationsEndpointTest.testCreateAndGetApplication:115
  NexmoIncomingPhoneNumbersEndpointTest.testGetAvailableCountries:105
  VoxboneAvailablePhoneNumbersEndpointTest.testSearchUSLocalPhoneNumbersWith501AreaCode:106
  DialForkTest.testDialForkNoAnswerExecuteRCML_ReturnedFromActionURL:1046
  TestDialVerbPartTwo.testDialClientAliceToBigDID:182
  TestDialVerbPartTwo.testDialClientAliceWithRecord:244
  TestDialVerbPartTwo.testDialClientAliceWithRecordAndStatusCallbackForApp:323
  TestDialVerbPartTwo.testDialClientAliceWithRecordAndStatusCallbackForAppForThreeCalls:425
  TestDialVerbPartTwo.testDialNumberGeorge:804
  TestDialVerbPartTwo.testDialNumberGeorgePassInitialCallerId:1009
  TestDialVerbPartTwo.testDialNumberGeorgeWithWrongScreeningUrl:857
  TestDialVerbPartTwo.testDialNumberGeorge_403Forbidden:916
  TestDialVerbPartTwo.testDialNumberGeorge_404_OnBye:958
  TestDialVerbPartTwo.testRecordWithActionAndStatusCallbackForAppWithBobSendsFinishKey:721
  TestDialVerbPartTwo.testRecordWithActionAndStatusCallbackForAppWithDisconnectFromBob:646
  TestMultipartContent.testDialConference:210
  UserAgentManagerTest.registerUserAgentWithOptionsPing:207
Tests in error: 
  NoAuthRegisterClientTest.before:124 » InvalidArgument java.net.BindException: ...
  NoAuthRegisterClientTest.before:124 » InvalidArgument java.net.BindException: ...
  RegisterClientTest.before:128 » InvalidArgument java.net.BindException: Can't ...
  RegisterClientTest.before:128 » InvalidArgument java.net.BindException: Can't ...
  RegisterClientTest.before:128 » InvalidArgument java.net.BindException: Can't ...

Tests run: 247, Failures: 17, Errors: 5, Skipped: 6`

**Comment by deruelle** [comment]
@maria-farooq your message on the failing tests is unclear, were those tests failing before the fixes ?

**Comment by gvagenas** [comment]
@maria-farooq I checked you patch here and looks good.
Did you checked why the above tests you list, are failing? Doesn't look to me that the patch here is the reason for these failing tests, please check for exceptions and errors in the logs.

Also, the issue here is related to the one i opened #1081 , please check this one also

Thanks
George

**Comment by maria-farooq** [comment]
@gvagenas thanks,

one very strange thing happens, whenever i execute testsuit it fails for different reason, it takes 1:15 hours to complete on average which make it hard to point why it behave like that. 
#1081 ok Letme lookinto it, reproduce it and check this patch on that

**Comment by gvagenas** [comment]
@maria-farooq for the testsuite try to run each test class individually. You don't need to run all test tests all the time. You can use your IDE and run tests individually depending on what you working on, for example if you are working on Call actor, VoiceInterpreter etc, run the tests in the telephony, if you are working on REST API run the tests in the http package etc.
When you finish your work, run the full testsuite from command line using "mvn surefire-report:report"

**Comment by maria-farooq** [comment]
thanks @gvagenas, will do that

**Comment by maria-farooq** [comment]
@gvagenas i executed testclasses in telephony package individually via IDE:

- No test is failing.
- NoAuthRegisterClientTest  & RegisterClientTest are giving error ("BindExceptions") but this same error is faced on master as well so its not regard for this branch.
- Apart from these 2 classes all tests are passing

**Pull request merged**
