### PR TITLE
Issue 5

### PR DESCRIPTION
**Pull request by maria-farooq**
@gvagenas please review

### CODE REVIEW

**Comment by deruelle** [comment]
@maria-farooq can you rebase against latest master as it seems your branch has conflicts

**Comment by maria-farooq** [comment]
yes, looking into it

**Comment by maria-farooq** [comment]
performing a round of testing after rebase and conflict resolution.

**Comment by gvagenas** [comment]
@maria-farooq thanks for the update here. Will review and provide feedback asap

**Comment by maria-farooq** [comment]
Thanks @gvagenas , some leftover is mentioned in a file todo.txt, we have to delete that file before merging. I am afraid i wont be able to work on that until friday. (due to an assignment at work)

**Comment by gvagenas** [comment]
@maria-farooq, you work so far is very good and in the right path. 

One important comment is to make sure that a CDR can be created with null conference_sid, such as calls that doesn't participate to a conference room. Currently all DB operations for CDR fail if there is no conference_sid.

Same thing for CallsEndpoint, you should handle the situation where the conference_sid is null.

Also at the new conference table, better change the "conference_sid" to "sid" to conform with the other tables.

**Comment by maria-farooq** [comment]
thanks @gvagenas I will modify accordingly.

**Comment by maria-farooq** [comment]
Hi @gvagenas  I changed conference_sid to sid, and tested my branch with a simple call application (with a simple say verb in response) and CDRs are populating/updating fine. I updated the restcomm.testsuit as well.

**Comment by deruelle** [comment]
@maria-farooq can you rebase against latest master as it seems there is conflicts ?

**Comment by gvagenas** [comment]
Hi @maria-farooq , see my comments below:

- At CallsEndpoint when preparing "filterForTotal" you use "conferenceSid" https://github.com/maria-farooq/Restcomm-Connect/blob/issue-5/restcomm/restcomm.http/src/main/java/org/mobicents/servlet/restcomm/http/CallsEndpoint.java#L215 while when preparing the regular "filter" you don't use it. Why is that? To my opinion we should not use conferenceSid when getting the call records, unless if I am missing something here.
- At VoiceInterpreter line 2110 - https://github.com/RestComm/Restcomm-Connect/blob/c7ed706d801014351ddd9e1178bf16c53fbabf94/restcomm/restcomm.interpreter/src/main/java/org/mobicents/servlet/restcomm/interpreter/VoiceInterpreter.java#L2111-L2111 - the conferenceDetailRecord should be update outside the if (callRecord != null) 


Last, I see you are missing test cases in the testsuite to test the new Conference API, I guess you are working on that, right? 

Regards
George

**Comment by maria-farooq** [comment]
Hi @gvagenas 

Thanks for your comment, i will analyze, change, test and commit accordingly.

Regards,
Maria

**Comment by maria-farooq** [comment]
Following 2 test fails even when i run testsuit on master@Restcomm/Restcomm-Connect.
How can i get around it.

```
Results :
Failed tests: 
  NexmoIncomingPhoneNumbersEndpointTest.testGetAvailableCountries:105
  VoxboneAvailablePhoneNumbersEndpointTest.testSearchUSLocalPhoneNumbersWith501AreaCode:106
Tests in error: 
  NoAuthRegisterClientTest.before:124 » InvalidArgument java.net.BindException: ...
  NoAuthRegisterClientTest.before:124 » InvalidArgument java.net.BindException: ...
  RegisterClientTest.before:128 » InvalidArgument java.net.BindException: Can't ...
  RegisterClientTest.before:128 » InvalidArgument java.net.BindException: Can't ...
  RegisterClientTest.before:128 » InvalidArgument java.net.BindException: Can't ...

Tests run: 245, Failures: 2, Errors: 5, Skipped: 6
```

**Comment by maria-farooq** [comment]
will resolve conflicts it in a while

**Comment by deruelle** [comment]
woot ! Great PR contribution. Thanks @maria-farooq for the hard work on this one and @gvagenas for merging that in time for 7.8.0 !

**Pull request merged**
