### PR TITLE
Asciidoc conversion of "How to use Olympus with Restcomm"

### PR DESCRIPTION
**Pull request by malihanaveed**
@deruelle  Please review the file converted to asciidoc.

#issue-1064

### CODE REVIEW

**Comment by deruelle** [comment]
@malihanaveed Thanks, I have a some comments below:

1. Were you able to run the preview locally through `mvn clean install` in your local Restcomm-Connect/restcomm/restcomm.docs/sours-asciidoc directory ?

2. Were you able to run Olympus app yourself ? 

3. It seems you used different sub sections for each of the sections from the original document. This seem not to display that well on 2 things. First the Table of contents don't include them see pic attached 
screenshot from 2016-05-16 18 27 47
 and second the background behind the section Call from bob is yellow... see pic attached here 
![screenshot from 2016-05-16 18 24 30](https://cloud.githubusercontent.com/assets/54279/15295980/910a4b3c-1b93-11e6-8c89-e8db77890af6.png

4. I see in one place Olymous instead of Olympus

5. the link at the bottom https://github.com/Mobicents/olympus should be changed by https://github.com/Restcomm/olympus and the other link doesn't seem to display well

**Comment by malihanaveed** [comment]
1. No, I couldn't do that. Instead I updated the document in AsciidocFx --> commit the issue through GitHub desktop app and pushed it here. 
2. No, I faced issues trying to download restcomm, but will do so to understand the process better
3. Yes, I tried having different sub sections to highlight and differentiate examples, but since it did not work well I have updated in the new commit. 
4. & 5. I have updated the link and typo error mistakes as well.

Thankyou for the detailed review.

**Comment by deruelle** [comment]
1. ok feel free to ping me on gitter so I can explain you how to do it.
2. As discussed on gitter, let's try to migrate this content http://docs.telestax.com/restcomm-docker-quick-start-guide so that you can run Olympus and improve the content of this article you just migrated. I assigned https://github.com/RestComm/Restcomm-Connect/issues/1086 to you.
3. It's a bit better but I think you should make `Calling Restcomm with WebRTC` a section at the same level as `Pre-requisites` and have another Section called `Messaging with Restcom WebRTC` and under those sections `Calling from bob` and `Chatting with bob` should be sub-sections respectively. Right now the structure of the document doesn't make enough sense.

**Comment by deruelle** [comment]
@malihanaveed for you information, I merged the work and migrated all content from http://docs.telestax.com/restcomm-pages/ to asciidoc in 
https://github.com/RestComm/Restcomm-Connect/tree/master/restcomm/restcomm.docs/sources-asciidoc

**Pull request closed without merging**
