### PR TITLE
Display Version number with release date using RestComm version API #117

### PR DESCRIPTION
**Pull request by muhammadbilal19**
Please review my changes for this issue and let me know with your comments. #117

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @muhammadbilal19. @otsakir can you review ?

**Comment by otsakir** [comment]
sure @deruelle , will take care of it.

**Comment by otsakir** [comment]
@muhammadbilal19, it seems there is a bug with the date conversion. The angular 'date' filter takes the source date as unix time but the actual Version response is like the following:
```
{
  "Name": "Mobicents Restcomm",
  "Version": "7.8.0-SNAPSHOT",
  "Revision": "r522d79dd943b48634717ec205567344c90fe9513",
  "Date": "201606140753"
}
```

and produces the following output:

RestComm v7.8.0-SNAPSHOT release date : 22/05/1976

probably an error in the conversion.You think you can provide a fix for that and update the PR ?

**Comment by muhammadbilal19** [comment]
@otsakir thanks for the update yes i can fix this issue. so what is the desired output. 

RestComm v7.8.0-SNAPSHOT release date : 201606140753  ??

**Comment by muhammadbilal19** [comment]
@otsakir fix for date format is now available. Please have a look.

**Comment by otsakir** [comment]
@muhammadbilal19, thanks for taking care of that. Your fix is merged ;-)

**Comment by muhammadbilal19** [comment]
Great! thanks @otsakir

**Pull request merged**
