### PR TITLE
784 Issue - Allow Restcomm client authentication with the user ID and password of a Restcomm account user

### PR DESCRIPTION
**Pull request by thinhly197**

### CODE REVIEW

**Comment by deruelle** [comment]
@thinhly197 is this now complete ? Can @gvagenas review ?

**Comment by thinhly197** [comment]
@deruelle yes, I already pushed all my changes

**Comment by deruelle** [comment]
thanks @thinhly197 
@gvagenas can you please review ?

**Comment by deruelle** [comment]
@thinhly197 can you rebase the work to latest master as it seems there is conflicts

**Comment by gvagenas** [comment]
@thinhly197 I updated and merged with master. The new branch is "issue784" and you should sync your work with that master as it contains the proper tests for the issue.

The issue is not merged back to master for now because of a design issue that needs to be discussed. I will comment for that on the #784

**Comment by gvagenas** [comment]
Hi @thinhly197 , please rebase your branch with master so we can merge this PR.

Thanks
George

**Pull request merged**
