### PR TITLE
Issue 1312

### LINKED ISSUE #1312: Support Live Call Modification in a cluster

### PR DESCRIPTION
**Pull request by maria-farooq**
Please also review https://bitbucket.org/telestax/telscale-restcomm/pull-requests/24/issue-1312/diff
Added solution doc at telscale
fixes #1312 #1907

### CODE REVIEW

**Comment by maria-farooq** [comment]
Hi @gvagenas 

Yes i ran CallLifeCycleTests locally, and i saw no problem in bootstrap.
Now again i ran it and did not notice any issue they executed normally and passed.
However I also started https://mobicents.ci.cloudbees.com/job/RestComm-For-Specific-Branch/43 with full testsuit run

Letme share status of this build.

Thanks & Regards
Maria

**Comment by maria-farooq** [comment]
@gvagenas ci job is finished and i will checked fail test cases.

**Comment by maria-farooq** [comment]
ok @gvagenas i will check it
Thanks

**Comment by maria-farooq** [comment]
found the issue one of header is not being generated properly
`X-RestComm-CallSid: IDd5eae1c8ee8e47a8981ef94ad510f798-IDd5eae1c8ee8e47a8981ef94ad510f798-CAaa841b6534b04c93974059d8114b0424`
working on it

**Comment by maria-farooq** [comment]
**FAILING on this branch (But passing on master)**

```
 org.restcomm.connect.testsuite.http.LiveCallModificationTest.redirectCallInConferenceMuted	24 sec	1
 org.restcomm.connect.testsuite.telephony.CallLifecycleTest.testDialNumberPstn_404NotHere	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialActionAnswerDelayTest.testDialActionInvalidCall	12 sec	1
 org.restcomm.connect.testsuite.telephony.ImsClientsDialAnswerDelayTest.testWebRTCClientIncomingBusy	40 sec	1
 org.restcomm.connect.testsuite.provisioning.number.vi.IncomingPhoneNumbersEndpointTest.testPurchaseTollFreePhoneNumberNoPhoneNumberFound	0.25 sec	1
 org.restcomm.connect.testsuite.provisioning.number.vi.IncomingPhoneNumbersEndpointTest.getIncomingPhoneNumbersListUsingPageSize	0.76 sec	1
```

**FAILING on this branch (But Passing Locally)**

```
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerButHenriqueStatusCallbackOnAll	15 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerButHenriqueStatusCallbackOnAllPost	12 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerButHenriqueStatusCallbackOnAllPostWithTimeout	12 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerExecuteRCML_ReturnedFromActionURLWithStatusCallbacks_BobDisconnects	15 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerExecuteRCML_ReturnedFromActionURLWithStatusCallbacks_AliceDisconnects	12 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackAliceDisconnects	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackMethodGET	11 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackBobDisconnects	11 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackOnlyInitiatedAnswerEvent	11 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackOnlyRingingCompleted	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackDialSip	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackDialNumber	11 sec	1

```

**Comment by maria-farooq** [comment]
now running `FAILING on this branch (But passing on master)` again locally

**Comment by maria-farooq** [comment]
**FAILING on this branch as per CI (But Passing Locally)**

```
 org.restcomm.connect.testsuite.telephony.CallLifecycleTest.testDialNumberPstn_404NotHere	10 sec	1
 org.restcomm.connect.testsuite.http.LiveCallModificationTest.redirectCallInConferenceMuted	24 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerButHenriqueStatusCallbackOnAll	15 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerButHenriqueStatusCallbackOnAllPost	12 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerButHenriqueStatusCallbackOnAllPostWithTimeout	12 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerExecuteRCML_ReturnedFromActionURLWithStatusCallbacks_BobDisconnects	15 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialForkNoAnswerExecuteRCML_ReturnedFromActionURLWithStatusCallbacks_AliceDisconnects	12 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackAliceDisconnects	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackMethodGET	11 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackBobDisconnects	11 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackOnlyInitiatedAnswerEvent	11 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackOnlyRingingCompleted	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackDialSip	10 sec	1
 org.restcomm.connect.testsuite.telephony.DialStatusCallbackTest.testDialStatusCallbackDialNumber	11 sec	1
 org.restcomm.connect.testsuite.telephony.ImsClientsDialAnswerDelayTest.testWebRTCClientIncomingBusy	40 sec	1
 org.restcomm.connect.testsuite.provisioning.number.vi.IncomingPhoneNumbersEndpointTest.testPurchaseTollFreePhoneNumberNoPhoneNumberFound	0.25 sec	1
 org.restcomm.connect.testsuite.provisioning.number.vi.IncomingPhoneNumbersEndpointTest.getIncomingPhoneNumbersListUsingPageSize	0.76 sec	1
```

**There is no test found that is failing on this branch but passing on master**

**Comment by maria-farooq** [comment]
@gvagenas i rechecked branch and updated accordingly
here is link to latest testsuit result `https://mobicents.ci.cloudbees.com/job/RestComm-For-Specific-Branch/72/`

There are some tests failing in comparison to master but they are all passing locally
There is no test found that is failing on this branch but passing on master
We are good to merge both telscale and restcomm PRs

**Comment by maria-farooq** [comment]
look for `https://mobicents.ci.cloudbees.com/job/Restcomm-Testsuite-Specific-Branch/5/` when finishes

**Comment by maria-farooq** [comment]
Hi @gvagenas i update branch with master and ran testsuit again.
here is online result `https://mobicents.ci.cloudbees.com/job/RestComm-For-Specific-Branch/83/testReport/`
the difference of test with master were executed again on my local machine and all are passing. here is list `https://docs.google.com/spreadsheets/d/1dZUfKbAt4BJj2L_6AWDsLF1AccqTgMm8CFKlXETQNdc/edit#gid=1547996930` and i am also attaching screen shots of passing tests.
[Test-Result-Archive.zip](https://github.com/RestComm/Restcomm-Connect/files/1173224/Test-Result-Archive.zip)

**Comment by maria-farooq** [comment]
please note: results are consistent with last run and imo we are good to merge it..

**Comment by gvagenas** [comment]
Thanks @maria-farooq, PR is ready to be merged

**Pull request closed without merging**
