### PR TITLE
Implement message, recording, notification, transcription filter on server side following this issue: https://github.com/RestComm/Restcomm-Connect/issues/1395

### PR DESCRIPTION
**Pull request by forever3000**
Fix this issue https://github.com/RestComm/Restcomm-Connect/issues/1395

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @forever3000. @otsakir can you please review ?

**Comment by forever3000** [comment]
Hi @otsakir ,
Sorry for make 2 commits in one pull request. Please help me review them.
Thanks

**Comment by otsakir** [comment]
@forever3000 ,thanks for submitting the patch. I will review asap and let you know.

**Comment by otsakir** [comment]
Hi @forever3000. 

Due to heavy load, I plan to start reviewing your patch next Wednesday. I hope that's ok with you.

**Comment by forever3000** [comment]
Hi @otsakir  sure
Thanks

**Comment by otsakir** [comment]
Hi @forever3000. Thanks for your patience. I did a first run through your patch. Great work there. 

I noticed however there are no integration tests for the added functionality. Obviously because there were no test classes already in place. Also, no documentation is included. You think you could provide those too?

For testing, we mostly do integration testing using arquilian. It's all about adding the test class, override the default restcomm.script with another one from /resources with proper sample data and running the test. 

You can get a rough idea of how this works by looking into CallsEndpointTest.java. Here are some more comments to help you get the feel of it.

* The createWebArchiveNoGw() method at the end builds the custom binary to be tested. 
* All @Test-anotated methods do the actual testing typically by hiting the binary using a REST client and validating the responses. 
* You could also create a tool to host all client requests like RestcommCallsTool or use jersey directly as illustrated in RoleSensitiveTest.java.
* You could extend EndpointTest to save you from writing some boilerplate code too. It's not much saving though.

Orestis

**Comment by forever3000** [comment]
Hi @otsakir ,

Thank for your review and recommendation. I will try to investigate then provide test code for added functionality. Maybe I will ask something if stuck somewhere.

Thanks and Best Regards,
Vu Nguyen

**Comment by forever3000** [comment]
Hi @otsakir ,

I got clear to implement the test classes for added functionality. However there's already SmsEndpointTest class in restcomm.connect.testsuite.sms , should I create new test class for sms in restcomm.connect.testsuite.http or add more test cases to current sms test class. 
About the documentation, do you have any form or template?

Thanks and Best Regards,
Vu Nguyen

**Comment by otsakir** [comment]
@forever3000 sounds great!

**Regarding 1**,

there is no automated tool to produce these records. I suppose for Calls, they have been copied out of production environments. This is not an option in your case. I would go with taking a sample message/notification/transcriptions record from the script file and replicating it several times. Then, manually,  make the sid unique (values like SM00000000000000000000000000000001, SM00000000000000000000000000000002 should work to make your life easier) and also play a little with the dates, day-of-month etc. Then, when it comes to paging, use a small page size in your tests to verify proper operations of paging functionality. If that's the case, you can get away with 30-40 or maybe less records for each entity. It's not the best option but test-wise it covers most aspects i believe. You think that would work ?

**Regarding 2**, 

as you will probably have noticed, restcomm documentation is part of our codebase and is written in asciidoc. The *Calls API* doc page seems the closest existing part documentation. *List filter* and *Paging Information* sections are what you need to supply i think. 

Here they are:

https://github.com/RestComm/RestComm-Connect/blob/879c3c07f1235e3b74516b34b0d677059bf5044e/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc/api/calls-api.adoc#list-filter

https://github.com/RestComm/RestComm-Connect/blob/879c3c07f1235e3b74516b34b0d677059bf5044e/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc/api/calls-api.adoc#paging-information

So, it comes down to filling up the respective *-api.adoc documents under `/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc`.

I hope this helps you move forward. Ping me if you need any more feedback. I will be available tomorrow (friday) and then on Jan 4th.

**Comment by forever3000** [comment]
Hi @otsakir ,

Thank for your very good support. I created more than 30 records for message and recording, every test cases run well. However I can not create record for notification and transcription. Example sql for notification:
`INSERT INTO "restcomm_notifications" VALUES('N1b88ccff6c9e04f989de9415a555ad84c','2013-08-30 16:28:33.403000000','2013-08-30 16:28:33.403000000','AC20000000000000000000000000000000','CA5EB00000000000000000000000000002','2012-04-24',1,0,'http://docs.telestax.com/rvd-workspace-upgrade','Workspace migration skipped in 2016-12-28 21:12:25.758','2013-08-30 16:28:33.403000000',NULL,NULL,NULL,NULL,NULL,'/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Notifications/NOb88ccff6c9e04f989de9415a555ad84d.json')`

I'm investigating and hope you can give me any idea. If everything is ok, I will commit all test codes and documents also in next week.

Thanks and Best Regards,
Vu Nguyen

**Comment by forever3000** [comment]
Hi @otsakir 

Thank for your very good recommendations. I have finish test code as well as documentation for sms, recording, notification and transcription filter. Please help me review them.

Thanks and Best Regards,
Vu Nguyen

**Comment by forever3000** [comment]
Hi @otsakir

Thank for your very good recommendations. I have finish test code as well as documentation for sms, recording, notification and transcription filter. Please help me review them.

Thanks and Best Regards,
Vu Nguyen

**Comment by otsakir** [comment]
Hi @forever3000!

I've started reviewing your work and will also merge in latest changes from AdminUI revamp. I will get back to you as soon as it's done.

Thanks

**Comment by otsakir** [comment]
@forever3000 , the review is almost finished. Master branch has been merged into your code and some fixes have been provided for the UI layer and the testsuite. I've noticed however that there are no Mybatis query files provided for the _maria_ DB layer. Hsql is fine.

You think you could provide these too?

They are located under restcomm/restcomm.application/src/main/webapp/WEB-INF/scripts/mariadb/sql

Other that that, merging went smooth. Great job there!

Btw, you can pull the merged version of the code from _forever3000-master_ branch from upstream repo (https://github.com/RestComm/Restcomm-Connect.git). Better to base your last touch on that if you decide to move forward.

Finally, i'm baking a binary with the latest version of this branch accessible under:
https://mobicents.ci.cloudbees.com/view/RestComm/job/RestComm-For-Specific-Branch/20/
in case it is of any value to you.

Regards

**Comment by deruelle** [comment]
@forever3000 any progress on @otsakir latest comments ?

**Comment by forever3000** [comment]
Hi @otsakir ,
Thank for your very good comment. Sorry for a bit late. Please help me review and merge this code.

Hi @deruelle ,
Yes, Already finish.

**Comment by otsakir** [comment]
@forever3000, your branch has been reviewed and minor fixes applied. Thanks for contributing this!
 :+1:

@gvagenas , the patch is clear from my side. Minor manual testing has been done for mariadb too. You may proceed with merging to master. I've also committed minor fixes on top the head of the PR on main Restcomm repo:

https://github.com/RestComm/Restcomm-Connect/tree/forever3000-master

**Comment by deruelle** [comment]
@gvagenas can you review as well as it was approved by @otsakir ?

**Pull request merged**
