### PR TITLE
1180

### PR DESCRIPTION
**Pull request by muhammadbilal19**
I fix the issue #1180, along with somethings related to code formatting and few code reusability things  like, create few methods to reuse like playBeep,build waitUrl etc. 

I tested this issue according to my best knowledge of this application and if you still see any issue feel free to comment.

### CODE REVIEW

**Comment by muhammadbilal19** [comment]
@gvagenas sorry i didn't see before fixing it that you assigned this issue to yourself. Please feel free to ignore my changes if you already done with this issue :)

**Comment by muhammadbilal19** [comment]
I can see that @gvagenas  already merge changes for this issue to master branch so please ignore this pull request :)

**Comment by gvagenas** [comment]
@muhammadbilal19 thanks for your patch here, as you saw I had already patched this issue.

**Comment by muhammadbilal19** [comment]
no worries @gvagenas.

**Comment by deruelle** [comment]
@muhammadbilal19 feel free to sync up with the team on https://gitter.im/RestComm/Restcomm-discuss before taking on any issues to avoid this type of issues in the future

**Comment by muhammadbilal19** [comment]
Sure @deruelle

**Pull request closed without merging**
