### PR TITLE
Issue1496 account password

### PR DESCRIPTION
**Pull request by otsakir**

### CODE REVIEW

**Comment by gvagenas** [comment]
@otsakir please merge with master and resolve conflict

**Comment by gsaslis** [comment]
@otsakir doing some _more_ housekeeping here... is this still a valid PR ?

**Comment by otsakir** [comment]
I don't think it's valid @gsaslis. @gvagenas  , @maria-farooq can you confirm you won't be need this old attempt in any way ?

**Comment by gsaslis** [comment]
ok, thanks @otsakir . 

Closing for now. if @gvagenas or @maria-farooq feel they do, we can reopen.

**Pull request closed without merging**
