### PR TITLE
Issue 856

### PR DESCRIPTION
**Pull request by muhammadbilal19**
Please review and share you comments about my changes related to sub accounts grid in AdminUI #856.  Along with this i also updated the **ui-bootstrap** library as i observed that pagination which is currently being used on LOGS _ NOTIFICATIONS was not working as our ui-bootsrap library was bit old. I updated the to **0.14.3** . I also fix the pagination issue of logs notification page in this branch.

if upgrade of that ui-bootstrap library required some extra things or create some issues in other application let me know.

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @muhammadbilal19 @otsakir @gvagenas can you review as time permits ?

**Comment by otsakir** [comment]
Great work on that @muhammadbilal19. I will let  you know as soon as it's merged!

Thanks

**Comment by deruelle** [comment]
@otsakir were you able to review and merge this one ?

**Comment by otsakir** [comment]
Not yet @deruelle . It's planned for 7.9.0.

**Comment by otsakir** [comment]
@muhammadbilal19, i've merged your patch. Great work there!  ;-)

Thanks for contributing!

**Pull request merged**
