### PR TITLE
Fix issue : AdminUI DIDs and Clients details form should resemble in

### PR DESCRIPTION
**Pull request by muhammadbilal19**
Please review the changes for UX #1114. 
Fix one extra thing when client deleted from client deteilas form,after successfully deletion of client it will be return back to the client list.

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @muhammadbilal19  ! @otsakir can you review ?

**Comment by otsakir** [comment]
sure @deruelle. @muhammadbilal19, i will review and get back to you. Thanks for the contribution!

**Comment by otsakir** [comment]
@muhammadbilal19 i reviewed and merged your patch. It worked just fine!

**Comment by muhammadbilal19** [comment]
@otsakir thanks :)

**Pull request merged**
