### PR TITLE
Issue #1723: Endpoint uri inconsistencies 

### PR DESCRIPTION
**Pull request by abdulazizali77**
@otsakir please have a look
-removes rootUri from uri and subresource uris
This fixes
   Accounts
   Applications
   Clients
   Gateways
   IncomingPhoneNumbers
   OutgoingCallerIds
   SmsMessages

   Calls paging uris
   Conferences paging uris
   ConferenceParticipants paging uris

   AccountConverter
   CallDetailRecordConverter
   ConferenceDetailRecordConverter
   ConferenceParticipantConverter

-This is missing regression test(s), another TechDebt i will address
-Might have to have a complete look at the design of the Endpoints i feel, maybe use UrlBuilder for uri or just use request.getServletPath() + info.getPath()

### CODE REVIEW

**Comment by otsakir** [comment]
ok @abdulazizali77 . Thanks for taking the step to clean up this tech debt. Let me look into your patch and get back to you.

**Comment by otsakir** [comment]
@abdulazizali77 , the patch seems fine. I also ran manual tests and the responses have greatly improved in terms of consistency (there are still tech-debt issues  of course but they are out of the scope of this PR). I also wait for the testsuite to finish but i don't expect major regressions there. 

However, i noticed the docs are out of sync (a lot still contain the /restcomm/* prefix). You think you could take a quick look there ? If you decide to take care of this the asciidoc pages i'm referring to are here:

https://github.com/RestComm/RestComm-Connect/tree/bcf9c73e67bd70fa07d8fb3348a1a5d9df0dbb12/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc/api

Thanks for the contribution. I'll let you know of any progress.

**Comment by abdulazizali77** [comment]
@otsakir i can look at the docs, do you think it should be done with this PR or a new PR? Im more inclined for a new PR. Also yes i was going to open a separate Issue+PR for regression tests

**Comment by otsakir** [comment]
@abdulazizali77, thanks for the updates in the docs. 

I've applied minor fixes in the testsuite and docs too. I'll assign the PR to @gvagenas , who will do the final merge.

Thanks for contributing! :+1:

**Comment by abdulazizali77** [comment]
Thanks @otsakir ! 
I havent looked at your new patch, but i found out that potentially NotificationsEndPoint _might_ have an _incorrect_ uri starting with "/restcomm" it uses theruntime config "error-dictionary-uri" which starts with "/restcomm"
This could be a documentation error or an endpoint error or both. The uri description for NotificationsEndPoint isnt particularly helpful, from what i understand of the code, the Uri refers to an Error url/uri but am unsure of its usage, the documentation however i think was copypasted from AccountEndPoint

**Comment by otsakir** [comment]
Hi @abdulazizali77. 

As far as i checked, `error-dictionary-uri` is used to initialize the _more_info_ property. For example:

https://github.com/RestComm/RestComm-Connect/blob/5fb42461a3cfbff35a2c976996fd8500557a5b49/restcomm/restcomm.interpreter/src/main/java/org/restcomm/connect/interpreter/BaseVoiceInterpreter.java#L582-L582

In any case. Let's not make this part of this PR. It's cooked and ready for final review and merge.

**Comment by abdulazizali77** [comment]
@otsakir Youre right, i was delusional about error-dictionary-uri it only goes to more_info. Thank you for the fixes of my fixes!

**Comment by abdulazizali77** [comment]
@gvagenas thanks!

**Pull request merged**
