### PR TITLE
Issue #1738 - Various EP fixes

### PR DESCRIPTION
**Pull request by abdulazizali77**
@otsakir Apologies for the slow update. This fixes 1, 3, 4. 
for 4a we could call `gson.disableHtmlEscaping()` in all EPs, but i did not do that in this PR.

I will address 2) in a separate PR

### CODE REVIEW

**Comment by deruelle** [comment]
@abdulazizali77 thanks. @otsakir can you review ?

**Comment by otsakir** [comment]
@abdulazizali77 sorry for the delay in merging. It has been for a good reason.

A discussion with the team has lead to some interesting conclusion. The fact that we store 'uri' in the DB is causing more trouble that gain. Why not produce this dynamically ? Maybe create a central mechanism, or customize the converters more. All required bits of information to produce the url are already there. Also in terms of performance, there is not much more involved than string concat which is already the case.

Also see https://github.com/RestComm/Restcomm-Connect/issues/1976 .

**Comment by otsakir** [comment]
@abdulazizali77 , after discussing with @gvagenas it seems that you need to strip the '/restcomm/' part from mariadb init scripts too (init.sql). 

@gvagenas can you confirm that ?

**Comment by abdulazizali77** [comment]
sorry i missed it! @otsakir @gvagenas, c'est done!

**Pull request merged**
