### PR TITLE
Restcomm 1741

### LINKED ISSUE #2844: Regex changes do not affect proper operation of USSD short code features (Fast dial)
In the past we've experienced that regex or organization changes broke USSD short code operation for fast dial feature (e.g. `*777*3#`). We then need to add test suite cases to make sure these changes don't affect this USSD dialing feature again. 

Tied to Jira issues _USSDGW-180_ and _RESTCOMM-1741_.

### PR DESCRIPTION
**Pull request by FerUy**
**What this PR does / why we need it**:
In the past we've experienced that regex or organization changes broke USSD short code operation for fast dial feature (e.g. `*777*3#`, `*999*1*1234#`, etc.). 
This PR adds a test suite case for USSD fast-dial feature.

**Which issue(s) this PR fixes**
Fixes #2844.

**Special notes for your reviewer**:
Tied to Jira issues _USSDGW-180_ and _RESTCOMM-1741_.

### CODE REVIEW

**Comment by jaimecasero** [comment]
im ok merging this PR...

**Comment by FerUy** [comment]
> im ok merging this PR...

So, @jaimecasero @gvagenas can we merge it then or am I missing something?

**Comment by jaimecasero** [comment]
https://cxs.restcomm.com/view/VVSSquad/view/ConnectCommunity/job/Restcom-CI-Multibranch/view/change-requests/job/PR-2845/lastCompletedBuild/testReport/   there are some test failures in this branch

**Comment by FerUy** [comment]
Thanks for feedback @jaimecasero :)

**Pull request merged**
